### ISSUE TITLE
加入iview-loader后仍然错误

### ISSUE THREAD

**Issue by ganlanshugod** [iview/iview-loader#6]
加入iview-loader 1.0.0 版本后，增加webpack.base.js中的配置
       `test: /\.vue$/,
        use: [
          {
            loader: 'vue-loader',
            options: vueLoaderConfig
          },
          {
            loader: 'iview-loader',
            options: {
                prefix: false
            }
          }]
      }`
仍然存在vue的错误提示，我使用的是vue最新版本的vue-cli生成的webpack项目
[Vue warn]: Do not use built-in or reserved HTML elements as component id: Circle
[Vue warn]: Do not use built-in or reserved HTML elements as component id: Switch

**Comment by icarusion** [comment]
下个 iview 版本修复此问题

**Comment by mcmf** [comment]
不更新了吗   还是报错

**Comment by mcmf** [comment]
@icarusion
